import tkinter 
from tkinter import *
from tkinter import messagebox
from tkinter import ttk
import pymysql
def showbillgenrateupdate():
 
    t=tkinter.Tk() 
    t.geometry('700x700')
    t.title('Billgenerate')
    r=Label(t,text='Bill Update Form',font=('arial',20),fg='red',bg='black')
    r.place(x=120,y=10)
    t.config(bg='orange')
    def updatedata():
        db=pymysql.connect(host='localhost',user='root',password='root',database='ims')
        cur=db.cursor()
        xa=int(e1.get())
        xb=e2.get()
        xc=e3.get()
        xd=e4.get()
        sql="update billgenrate set orderno='%s',custid='%s',billamount='%s' where custid=%d"%(xb,xc,xd,xa)
        cur.execute(sql)
        db.commit()
        db.close()
        messagebox.showinfo('hi','done')
        e1.delete(0,END)
        e2.delete(0,END)
        e3.delete(0,END)
    def finddata():
        db=pymysql.connect(host='localhost',user='root',password='root',database='ims')
        cur=db.cursor()
        xa=int(e1.get())
        sql="select orderno,custid,billamount from billgenrate where billno=%d"%(xa)
        cur.execute(sql)
        data=cur.fetchone()
        e2.insert(0,data[0])
        e3.insert(0,data[1])
        e4.insert(0,data[2])
        db.close()    
    a=Label(t,text='Billno')
    a.place(x=50,y=50)
    e1=Entry(t,width=20)
    e1.place(x=400,y=50)
    b=Label(t,text='Orderno')
    b.place(x=50,y=100)
    e2=Entry(t,width=20)
    e2.place(x=400,y=100)
    c=Label(t,text='Custid')
    c.place(x=50,y=150)
    e3=Entry(t,width=20)
    e3.place(x=400,y=150)
    d=Label(t,text='Billamount')
    d.place(x=50,y=200)
    e4=Entry(t,width=20)
    e4.place(x=400,y=200)
    bt1=Button(t,text='Update',width=20,command=updatedata)
    bt1.place(x=50,y=250)
    bt2=Button(t,text='find',width=20,command=finddata)
    bt2.place(x=250,y=250)
    t.mainloop()