import tkinter 
from tkinter import *
from tkinter import messagebox
from tkinter import ttk
import pymysql 
def showsuppliersave():
    t=tkinter.Tk() 
    t.geometry('700x700')
    t.title('Supplier')
    r=Label(t,text='Supplier Save Form',font=('arial',20),fg='red',bg='yellow')
    r.place(x=120,y=10)
    t.config(bg='brown')
    
    def savedata():
        db=pymysql.connect(host='localhost',user='root',password='root',database='ims')
        cur=db.cursor()
        xa=int(e1.get())
        xb=e2.get()
        xc=e3.get()
        xd=e4.get()
        xe=e5.get()
        xf=e6.get()
        sql="insert into supplier values (%d,'%s','%s','%s','%s','%s')" % (xa,xb,xc,xd,xe,xf)
        cur.execute(sql)
        db.commit()
        messagebox.showinfo('Hi','Saved')
        e1.delete(0,END)
        e2.delete(0,END)
        e3.delete(0,END)
        e4.delete(0,END)
        e5.delete(0,END)
        e6.delete(0,END)

    def checkdata():
            db=pymysql.connect(host='localhost',user='root',password='root',database='ims')
            cur=db.cursor()
            xa=int(e1.get())
            sql="select count(*) from supplier where supplierid=%d"%(xa)
            cur.execute(sql)
            data=cur.fetchone()
            if data[0]==0:
                messagebox.showinfo('hi','ok goahead')
            else:
                messagebox.showinfo('hi','Alreday Token')
                db.close()
    
    a=Label(t,text='Supplier id')
    a.place(x=50,y=50)
    e1=Entry(t,width=20)
    e1.place(x=400,y=50)
    btf=Button(t,text='Check',command=checkdata)
    btf.place(x=550,y=50)
    b=Label(t,text='Sname')
    b.place(x=50,y=100)
    e2=Entry(t,width=20)
    e2.place(x=400,y=100)
    c=Label(t,text='Address')
    c.place(x=50,y=150)
    e3=Entry(t,width=20)
    e3.place(x=400,y=150)
    d=Label(t,text='Email')
    d.place(x=50,y=200)
    e4=Entry(t,width=20)
    e4.place(x=400,y=200)
    f=Label(t,text='Phone')
    f.place(x=50,y=250)
    e5=Entry(t,width=20)
    e5.place(x=400,y=250)
    g=Label(t,text='Cat id')
    g.place(x=50,y=300)
    e6=Entry(t,width=20)
    e6.place(x=400,y=300)
    bt1=Button(t,text='Save',width=20,command=savedata)
    bt1.place(x=50,y=350)
    t.mainloop()